# Generated by Django 5.0.4 on 2024-04-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_wa', models.TimeField()),
                ('web_link', models.TimeField()),
                ('fb_link', models.TimeField()),
                ('ig_link', models.TimeField()),
                ('web_click', models.IntegerField(default=0)),
                ('fb_click', models.IntegerField(default=0)),
                ('ig_click', models.IntegerField(default=0)),
                ('web_checkout', models.IntegerField(default=0)),
                ('fb_checkout', models.IntegerField(default=0)),
                ('ig_checkout', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('platform', models.TextField()),
                ('date', models.DateTimeField()),
                ('id_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='app.link')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.product'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_uri', models.TextField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('comment', models.TextField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.product')),
            ],
        ),
    ]
