# Generated by Django 5.0.4 on 2024-04-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='fb_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='ig_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='no_wa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='web_link',
            field=models.TextField(),
        ),
    ]
